services:
  db:
    image: postgres:16.1-alpine
    container_name: nestjs-template-db
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@:5432/nestjs_template_db?sslmode=disable
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_template_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5440:5432"
    volumes:
      - nestjs_template_pg_data:/var/lib/postgresql/data

volumes:
  nestjs_template_pg_data: